name: LINT

on: 
  pull_request:
    branches: [ "main" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3 

          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ matrix.node-version }}
      - name : Cache
        uses: actions/cache@v3.0.10
        with:
          path: "/node_modules"
          key: node-modules-${{ hashFiles('package.json') }}
            
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: npm run lint
      - run: npm run check-types
      
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            *1st line of your message with bold*
            *2nd line of your message with bold, too*
            Application: *Write something to be put inside your message*. The below lines still are part of your message.          
            Branch: *${{ github.ref }}*
            Repository: *${{ github.repository }}*
            Owner: *${{ github.repository_owner }}*
    
