name: TEST

on: 
  push:
    branches: 
      - main
      - test
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    
    outputs:
      message: ${{ steps.*.outputs.build_message }}

    steps:
      - uses: actions/checkout@v3 

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ matrix.node-version }}
      - name : Cache
        uses: actions/cache@v3.0.10
        with:
          path: "./*"
          key: ${{ github.sha }}
            
      - run: npm ci
      - run: npm run build
     
      - if: success()
        id: set_success_message
        run: | 
          echo "::set-output name=build_message::--✅ BUILD completed successfully"  
        
      
      - name: send error message
        if: failure()
        id: set_error_message
        run: | 
          echo "::set-output name=build_message::--❌ BUILD completed with errors"  
           
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ matrix.node-version }}
        
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
          
      - run: npm run lint
      - run: npm run check-types
      
      - if: success()
        name: send success message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |         
            Branch: *${{ github.ref }}*
            Repository: *${{ github.repository }}*
            Owner: *${{ github.repository_owner }}*
            --✅ LINTING completed successfully

      - if: failure()
        name: send error message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |         
            Branch: *${{ github.ref }}*
            Repository: *${{ github.repository }}*
            Owner: *${{ github.repository_owner }}*
            --❌ LINTING completed with errors

  test: 
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
          
      - run: echo Hello world! Here will be placed my tests
      - run: npm run test
      
      - if: success()
        name: send success message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |         
            Branch: *${{ github.ref }}*
            Repository: *${{ github.repository }}*
            Owner: *${{ github.repository_owner }}*
            --✅ TESTING completed successfully

      - if: failure()
        name: send error message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |         
            Branch: *${{ github.ref }}*
            Repository: *${{ github.repository }}*
            Owner: *${{ github.repository_owner }}*
            --❌ TESTING completed with errors
            
  send-mesage: 
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build, lint, test]
  
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{needs.build.outputs.message}}
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |         
            Branch: *${{ github.ref }}*
            Repository: *${{ github.repository }}*
            Owner: *${{ github.repository_owner }}*
            --❌ LINTING completed with errors
